services:
  postgres:
    image: postgres:16-alpine
    container_name: microservices-postgres
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d

  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    container_name: microservices-eureka
    environment:
      SPRING_PROFILES_ACTIVE: local
    ports:
      - "8761:8761"

  student-service:
    build:
      context: .
      dockerfile: student-service/Dockerfile
    container_name: microservices-student
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - eureka-server
    ports:
      - "8081:8081"

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: microservices-user
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - eureka-server
      - postgres
    ports:
      - "8082:8082"

  gateway-service:
    build:
      context: .
      dockerfile: gateway-service/Dockerfile
    container_name: microservices-gateway
    environment:
      SPRING_PROFILES_ACTIVE: local
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"

volumes:
  postgres-data:
