apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-demo-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  ingressClassName: traefik
  rules:
    - host: microservices-demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: login-ui
                port:
                  number: 3000
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 8080
          - path: /eureka/
            pathType: Prefix
            backend:
              service:
                name: eureka-server
                port:
                  number: 8761
