apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login-ui
  template:
    metadata:
      labels:
        app: login-ui
    spec:
      containers:
        - name: login-ui
          image: microservices-demo/login-ui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: API_PROXY_TARGET
              value: http://gateway-service:8080
